---
- name: create package directory
  file:
    path: "{{ build_dir }}/dev-env"
    state: directory

- name: copy all tars
  shell: cp {{ build_dir }}/*.tar.gz {{ build_dir }}/dev-env

- name: copy all zips
  shell: cp {{ build_dir }}/*.zip {{ build_dir }}/dev-env

- name: copy vim bundles
  shell: cp -r {{ local_home }}/.vim {{ build_dir }}/dev-env

- name: copy dotfiles
  command: cp -r ~/dotfiles {{ build_dir }}/dev-env/

- name: copy this repo (dev-env)
  when: not offline
  git:
    repo: https://github.com/arw180/dev-env.git
    dest: "{{ build_dir }}/dev-env"

- name: create archive and place in {{ devenv_dir }}
  shell: tar czf dev-env.tar.gz dev-env; mv dev-env.tar.gz {{ devenv_dir }}
  args:
    chdir: "{{ build_dir }}"

- name: cleanup
  file:
    path: "{{ build_dir }}/dev-env"
    state: absent
  become: true
