---
- name: create package directory
  file:
    path: "{{ build_dir }}/dev-env"
    state: directory

- name: copy all tars
  shell: cp {{ build_dir }}/*.tar.gz {{ build_dir }}/dev-env

- name: copy all zips
  shell: cp {{ build_dir }}/*.zip {{ build_dir }}/dev-env

- name: copy vim bundles
  shell: cp -r {{ local_home }}/.vim {{ build_dir }}/dev-env
  become: true

- name: remove .git directories from vim bundles (some are write protected and
        cause copying to fail)
  shell: find {{ build_dir }}/dev-env/.vim  -type d -name "*.git" | xargs rm -rf
  become: true

- name: copy dotfiles
  shell: cp -r {{ local_home }}/dotfiles {{ build_dir }}/dev-env/
  become: true

- name: remove .git directories from dotfiles (some are write protected and
        cause copying to fail)
  shell: find {{ build_dir }}/dev-env/dotfiles  -type d -name "*.git" | xargs rm -rf
  become: true

- name: create archive and place in {{ devenv_dir }}
  shell: tar czf offline-files.tar.gz dev-env; mv offline-files.tar.gz {{ devenv_dir }}
  args:
    chdir: "{{ build_dir }}"

- name: cleanup
  file:
    path: "{{ build_dir }}/dev-env"
    state: absent
  become: true
