---
- hosts: all

  roles:
    - common
    - {role: offline, when: offline}
    - stow
    - ncurses
    - tmux
    - git
    - dotfiles
    - vim
    - zsh
    - htop
    - ldconfig
    - {role: package_env, when: create_package}
