---
- name: Clone dotfiles
  when: not offline
  git:
    repo: https://github.com/arw180/dotfiles.git
    dest: "{{ local_home }}/dotfiles"

- name: If offline, copy dotfiles
  when: offline
  command: cp -r {{ build_dir }}/dotfiles {{ local_home }}/

- name: Stow dotfiles for git
  shell: /usr/local/bin/stow git
  args:
    chdir: "{{ local_home }}/dotfiles"

- name: Stow dotfiles for vim
  shell: /usr/local/bin/stow vim
  args:
    chdir: "{{ local_home }}/dotfiles"

- name: Stow dotfiles for tmux
  shell: /usr/local/bin/stow tmux
  args:
    chdir: "{{ local_home }}/dotfiles"

- name: Stow dotfiles for zsh
  shell: /usr/local/bin/stow zsh
  args:
    chdir: "{{ local_home }}/dotfiles"

#- name: Stow dotfiles for bash
#  shell: /usr/local/bin/stow bash
#  args:
#    chdir: "{{ local_home }}/dotfiles"
