---
# Install dependencies
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - gcc
      - gcc-c++
      - unzip
  become: true


- name: Install dependencies required to build git
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - openssl-devel
      - curl-devel
      - expat-devel
      - gettext-devel
      - zlib-devel
      - perl-ExtUtils-MakeMaker
      - libselinux-python # required for ansible
  become: true

- name: Add stow libs to ldconfig
  copy:
   src: ld.conf
   dest: /etc/ld.so.conf.d/stow.conf
   owner: root
   mode: 0644
  become: true

- name: Reload ldconfig
  command: /sbin/ldconfig
  become: true

# todo: add /usr/local/lib and /usr/local/lib64 to /etc/ld.so.conf.d/dev-env.conf
#  then run ldconfig (see postgres_build task)
