---
- name: Download tmux source
  when: not offline
  get_url:
    url: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
    dest: "{{ build_dir }}"
    mode: 0644
    validate_certs: no

- name: Extract archive
  unarchive:
    src: "{{ build_dir }}/tmux-{{ tmux_version }}.tar.gz"
    dest: "{{ build_dir }}"
    copy: no

- name: Configure tmux
  command: chdir={{ build_dir }}/tmux-{{ tmux_version }} ./configure --prefix=/usr/local CFLAGS='-I/usr/local/include' CPPFLAGS='-I/usr/local/include/ncurses' LDFLAGS='-L/usr/local/lib'

- name: Make tmux
  command: chdir={{ build_dir }}/tmux-{{ tmux_version }} make

- name: Install tmux
  command: chdir={{ build_dir }}/tmux-{{ tmux_version }} make install prefix={{ stow_dir }}/tmux
  become: true

- name: Stow tmux
  command: chdir={{ stow_dir }} /usr/local/bin/stow tmux
  become: true

- name: Download tmux resurrect
  when: not offline
  get_url:
    url: https://github.com/tmux-plugins/tmux-resurrect/archive/v{{ tmux_resurrect_version }}.tar.gz
    dest: "{{ build_dir }}"
    mode: 0644
    validate_certs: no

- name: Extract archive
  unarchive:
    src: "{{ build_dir }}/tmux-resurrect-{{ tmux_resurrect_version }}.tar.gz"
    dest: "{{ devenv_dir }}"
    copy: no
