---
# Install dependencies
- name: Install dependencies
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon' or ansible_distribution == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - gcc
      - gcc-c++
      - unzip
  become: true

- name: Install dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - gcc
      - g++
      - unzip
      - make
  become: true


- name: Install dependencies required to build git
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon' or ansible_distribution == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    #- perl
      - openssl-devel
      - curl-devel
      - expat-devel
      - gettext-devel
      - zlib-devel
      - perl-ExtUtils-MakeMaker
      - libselinux-python # required for ansible
  become: true

- name: Install dependencies required to build git
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - openssl
      - libssl-dev
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - zlib1g-dev
        #- perl-ExtUtils-MakeMaker
      - python-selinux # required for ansible
  become: true

- name: Install ncurses-dev if on Ubuntu - not sure why this must be done
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - libncurses-dev

- name: Add stow libs to ldconfig
  copy:
    src: ld.conf
    dest: /etc/ld.so.conf.d/stow.conf
    owner: root
    mode: 0644
  become: true

# TODO: may need to run this after installing other libraries
- name: Reload ldconfig
  command: /sbin/ldconfig
  become: true

- name: Create dev-env
  file:
    path: "{{ devenv_dir }}"
    state: directory

