---
- name: Copy files for offline installation
  when: offline
  copy:
    src: dev-env.tar.gz
    dest: "{{ build_dir }}"
    force: yes

- name: Unarchive files for offline installation
  when: offline
  shell: tar xzf dev-env.tar.gz --strip 1
  args:
    chdir: "{{ build_dir }}"
