---
- name: Copy files for offline installation
  when: offline
  copy:
    src: offline-files.tar.gz
    dest: "{{ build_dir }}"
    force: yes

- name: Unarchive files for offline installation
  when: offline
  shell: tar xzf offline-files.tar.gz --strip 1
  args:
    chdir: "{{ build_dir }}"
