---
- name: Download vim source
  when: not offline
  get_url:
    url: https://github.com/vim/vim/archive/v{{ vim_version }}.tar.gz
    dest: "{{ build_dir }}"
    mode: 0644
    validate_certs: no

- name: Extract archive
  unarchive:
    src: "{{ build_dir }}/vim-{{ vim_version }}.tar.gz"
    dest: "{{ build_dir }}"
    copy: no

- name: Configure vim
  command: chdir={{ build_dir }}/vim-{{ vim_version }} ./configure --prefix=/usr/local

- name: Make vim
  command: chdir={{ build_dir }}/vim-{{ vim_version }} make

- name: Install vim
  command: chdir={{ build_dir }}/vim-{{ vim_version }} make install prefix=/usr/local/stow/vim
  become: true

- name: Stow vim
  command: chdir={{ stow_dir }} /usr/local/bin/stow vim
  become: true

- name: Clone Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    force: yes

# manually clone any other vim plugins that are required for the install to
# pass without warnings
- name: Clone Rainbow Parenthesis
  git:
    repo: https://github.com/kien/rainbow_parentheses.vim.git
    dest: ~/.vim/bundle/rainbow_parentheses.vim
    force: yes

- name: Clone Solarized
  git:
    repo: https://github.com/altercation/vim-colors-solarized.git
    dest: ~/.vim/bundle/vim-colors-solarized
    force: yes

- name: Install vim plugins
  shell: vim +PluginInstall +qall

- name: Create ftplugin directories
  file:
    path: ~/.vim/after/ftplugin
    recurse: true

- name: Get yaml settings
  copy:
    src: "yaml.vim"
    dest: ~/.vim/after/ftplugin/yaml.vim
    force: yes
